Added cloud provider to containers tutorial
While following along with the tutorial I ran into this error:
```
    error: Missing required configuration variable 'cloud:provider'
        please set a value using the command `pulumi config set cloud:provider <value>`
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

error: an error occurred while advancing the preview
```
Which was fixed with the proposed changes.