Fix wrong example (#17061)
When specifying autonaming configuration for a particular resource, we need to have a `pattern` field, otherwise Pulumi complains with the error message:

```
error: getting autonaming config: failed to parse autonaming config: invalid autonaming config structure: json: cannot unmarshal string into Go struct field providerConfigJSON.providers.resources of type autonaming.namingConfigJSON
``